# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
- task: DownloadPackage@1
  inputs:
    packageType: 'nuget'
    feed: '370bcbc3-45bb-40b8-8f2d-74f3d325a597/cd1cb68a-58d8-4ebe-8d18-9c549403cefd'
    view: '2e7d8174-2c48-4144-9f7b-b4de4196e888'
    definition: 'cd1cb68a-58d8-4ebe-8d18-9c549403cefd'
    version: '3.0.0-beta'
    downloadPath: '$(System.ArtifactsDirectory)'